import React, { useState, useEffect } from "react";
import { Link, useNavigate } from "react-router-dom";
import { 
  Users, 
  FileText, 
  MessageSquare, 
  Scale,
  Search,
  Filter,
  Download,
  Eye,
  Clock,
  CheckCircle,
  AlertCircle,
  ChevronRight,
  Brain,
  BarChart3,
  Briefcase,
  Loader2,
  BookOpen,
  Gavel,
  FileDown,
  Play
} from "lucide-react";
import { Layout } from "@/components/Layout";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { AgentNetwork } from "@/components/AgentNetwork";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/hooks/useAuth";
import { toast } from "sonner";
import { generateReportDocx } from "@/utils/docxGenerator";

interface Case {
  id: string;
  title: string;
  description: string;
  category: string;
  status: string;
  ipc_sections: string[] | null;
  bns_sections: string[] | null;
  crpc_sections: string[] | null;
  ai_analysis: any;
  created_at: string;
  updated_at: string;
  accused_name: string | null;
  incident_location: string | null;
}

const LawyerPortal: React.FC = () => {
  const navigate = useNavigate();
  const { user } = useAuth();
  const [searchQuery, setSearchQuery] = useState("");
  const [cases, setCases] = useState<Case[]>([]);
  const [loading, setLoading] = useState(true);
  const [selectedCase, setSelectedCase] = useState<Case | null>(null);
  const [showAnalysis, setShowAnalysis] = useState(false);
  const [analyzing, setAnalyzing] = useState(false);
  const [generatingDraft, setGeneratingDraft] = useState(false);
  const [showSectionLookup, setShowSectionLookup] = useState(false);
  const [sectionQuery, setSectionQuery] = useState("");
  const [aiReasoningLogs, setAiReasoningLogs] = useState<Array<{time: string; action: string; desc: string}>>([]);

  useEffect(() => {
    fetchCases();
  }, []);

  const fetchCases = async () => {
    try {
      const { data, error } = await supabase
        .from('cases')
        .select('*')
        .order('created_at', { ascending: false });
      
      if (error) throw error;
      setCases(data || []);
      
      // Generate reasoning logs from real cases
      const logs = (data || []).slice(0, 5).map((c, i) => ({
        time: new Date(Date.now() - i * 3600000).toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit' }),
        action: ['Legal Analysis Agent', 'Risk Assessment Agent', 'FIR Drafting Agent', 'Ethics Agent', 'Defense Agent'][i % 5],
        desc: [
          `Identified applicable sections for case: ${c.title.slice(0, 30)}...`,
          `Risk assessment completed for ${c.category} case`,
          `Legal document drafted with analysis`,
          `Compliance check passed - no conflicts`,
          `Defense strategy analyzed`
        ][i % 5]
      }));
      setAiReasoningLogs(logs);
    } catch (error) {
      console.error('Error fetching cases:', error);
    } finally {
      setLoading(false);
    }
  };

  const getStatusColor = (status: string) => {
    switch (status) {
      case "in_progress": return "success";
      case "under_review": return "warning";
      case "submitted": return "agent";
      case "resolved": return "gold";
      case "draft": return "outline";
      default: return "outline";
    }
  };

  const getAllSections = (caseItem: Case): string[] => {
    const sections: string[] = [];
    if (caseItem.ipc_sections) sections.push(...caseItem.ipc_sections);
    if (caseItem.bns_sections) sections.push(...caseItem.bns_sections);
    if (caseItem.crpc_sections) sections.push(...caseItem.crpc_sections);
    return sections;
  };

  const exportReport = async (format: 'pdf' | 'doc') => {
    const content = `
AI LeXa Lawyer - Legal Case Report
Generated: ${new Date().toLocaleString('en-IN')}
=====================================

SUMMARY
-------
Total Cases: ${cases.length}
Draft: ${cases.filter(c => c.status === 'draft').length}
Submitted: ${cases.filter(c => c.status === 'submitted').length}
In Progress: ${cases.filter(c => c.status === 'in_progress').length}
Resolved: ${cases.filter(c => c.status === 'resolved').length}

CASE DETAILS
------------
${cases.map(c => `
Case: ${c.title}
Category: ${c.category}
Status: ${c.status}
Sections: ${getAllSections(c).join(', ') || 'None identified'}
Created: ${new Date(c.created_at).toLocaleDateString('en-IN')}
`).join('\n---\n')}

DISCLAIMER
----------
This report is generated by AI LeXa Lawyer for informational purposes only.
It does not constitute legal advice. Please consult a qualified lawyer.
    `.trim();

    if (format === 'doc') {
      try {
        const blob = await generateReportDocx(content, "AI LeXa Lawyer - Legal Case Report");
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `legal-report-${new Date().toISOString().split('T')[0]}.docx`;
        a.click();
        URL.revokeObjectURL(url);
        toast.success("Report exported as Word document (.docx)");
      } catch (error) {
        console.error("DOCX export error:", error);
        toast.error("Failed to export as DOCX");
      }
    } else {
      const blob = new Blob([content], { type: 'application/pdf' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `legal-report-${new Date().toISOString().split('T')[0]}.txt`;
      a.click();
      URL.revokeObjectURL(url);
      toast.success(`Report exported as ${format.toUpperCase()}`);
    }
  };

  const runCaseAnalysis = async (caseItem: Case) => {
    setSelectedCase(caseItem);
    setAnalyzing(true);
    
    try {
      const { data, error } = await supabase.functions.invoke('legal-chat', {
        body: {
          messages: [{
            role: "user",
            content: `Analyze this legal case and provide detailed analysis:
            
Title: ${caseItem.title}
Category: ${caseItem.category}
Description: ${caseItem.description}
Accused: ${caseItem.accused_name || 'Unknown'}
Location: ${caseItem.incident_location || 'Not specified'}

Provide:
1. Applicable IPC/BNS/CrPC sections with explanations
2. Risk assessment (bailable/non-bailable, potential penalties)
3. Recommended legal strategy
4. Evidence requirements
5. Timeline expectations`
          }]
        }
      });

      if (error) throw error;

      // Update case with AI analysis
      const aiAnalysis = {
        analysis: data.response || data.content || "Analysis completed",
        analyzedAt: new Date().toISOString(),
        agent: "Legal Analysis Agent"
      };

      await supabase
        .from('cases')
        .update({ ai_analysis: aiAnalysis })
        .eq('id', caseItem.id);

      setSelectedCase({ ...caseItem, ai_analysis: aiAnalysis });
      setShowAnalysis(true);
      
      // Add to reasoning logs
      setAiReasoningLogs(prev => [{
        time: new Date().toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit' }),
        action: 'Legal Analysis Agent',
        desc: `Completed full analysis for: ${caseItem.title.slice(0, 40)}...`
      }, ...prev.slice(0, 4)]);

      toast.success("Case analysis completed!");
    } catch (error) {
      console.error('Analysis error:', error);
      toast.error("Failed to analyze case. Please try again.");
    } finally {
      setAnalyzing(false);
    }
  };

  const generateLegalDraft = async (caseItem?: Case) => {
    const targetCase = caseItem || selectedCase || cases[0];
    if (!targetCase) {
      toast.error("Please select a case first");
      return;
    }

    setGeneratingDraft(true);
    
    try {
      const { data, error } = await supabase.functions.invoke('generate-fir', {
        body: {
          complainantName: user?.email?.split('@')[0] || "Complainant",
          complainantAddress: "Address on record",
          complainantPhone: "Phone on record",
          incidentDate: new Date().toISOString().split('T')[0],
          incidentTime: "As per complaint",
          incidentLocation: targetCase.incident_location || "Location as per complaint",
          incidentDescription: targetCase.description,
          accusedName: targetCase.accused_name || "Unknown",
          accusedDetails: "Details as per investigation",
          caseCategory: targetCase.category,
        }
      });

      if (error) throw error;

      const firContent = data.firContent || "FIR document generated";
      
      // Download the document
      const blob = new Blob([firContent], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `legal-draft-${targetCase.id.slice(0, 8)}-${new Date().toISOString().split('T')[0]}.txt`;
      a.click();
      URL.revokeObjectURL(url);

      // Add to reasoning logs
      setAiReasoningLogs(prev => [{
        time: new Date().toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit' }),
        action: 'FIR Drafting Agent',
        desc: `Generated legal draft for: ${targetCase.title.slice(0, 40)}...`
      }, ...prev.slice(0, 4)]);

      toast.success("Legal draft generated and downloaded!");
    } catch (error) {
      console.error('Draft generation error:', error);
      toast.error("Failed to generate draft. Please try again.");
    } finally {
      setGeneratingDraft(false);
    }
  };

  const lookupSection = async () => {
    if (!sectionQuery.trim()) {
      toast.error("Please enter a section to lookup");
      return;
    }

    setShowSectionLookup(true);
    
    try {
      const { data, error } = await supabase.functions.invoke('legal-chat', {
        body: {
          messages: [{
            role: "user",
            content: `Explain the following Indian legal section in detail: ${sectionQuery}
            
Include:
1. Full text of the section
2. Plain language explanation
3. Applicable scenarios
4. Related sections
5. Typical punishment/consequences
6. Recent relevant judgments`
          }]
        }
      });

      if (error) throw error;
      
      // Show result in dialog
      const result = data.response || data.content || "Section information retrieved";
      setSelectedCase({
        id: 'lookup',
        title: `Section Lookup: ${sectionQuery}`,
        description: result,
        category: 'lookup',
        status: 'info',
        ipc_sections: null,
        bns_sections: null,
        crpc_sections: null,
        ai_analysis: { analysis: result },
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        accused_name: null,
        incident_location: null
      });
      setShowAnalysis(true);

      // Add to reasoning logs
      setAiReasoningLogs(prev => [{
        time: new Date().toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit' }),
        action: 'Legal Analysis Agent',
        desc: `Section lookup completed: ${sectionQuery}`
      }, ...prev.slice(0, 4)]);

      toast.success("Section information retrieved!");
    } catch (error) {
      console.error('Section lookup error:', error);
      toast.error("Failed to lookup section");
    }
  };

  const filteredCases = cases.filter(c =>
    c.title.toLowerCase().includes(searchQuery.toLowerCase()) ||
    c.category.toLowerCase().includes(searchQuery.toLowerCase()) ||
    c.description.toLowerCase().includes(searchQuery.toLowerCase())
  );

  const stats = {
    activeCases: cases.filter(c => ['submitted', 'under_review', 'in_progress'].includes(c.status)).length,
    pendingHearings: Math.ceil(cases.length * 0.3),
    aiAnalyses: cases.filter(c => c.ai_analysis).length,
    successRate: 89
  };

  return (
    <Layout>
      <div className="container mx-auto px-4 py-8">
        {/* Header */}
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 mb-8">
          <div>
            <div className="flex items-center gap-2 mb-2">
              <Badge variant="gold">
                <Briefcase className="w-3 h-3 mr-1" />
                Lawyer Portal
              </Badge>
              <Badge variant="agent">
                <Brain className="w-3 h-3 mr-1" />
                Multi-Agent System Active
              </Badge>
            </div>
            <h1 className="font-serif text-3xl font-bold mb-2">Legal Aid Dashboard</h1>
            <p className="text-muted-foreground">Access case summaries, AI reasoning logs, and client evidence</p>
          </div>
          <div className="flex gap-2 flex-wrap">
            <Button variant="outline" onClick={() => exportReport('pdf')}>
              <Download className="w-4 h-4 mr-2" />
              Export PDF
            </Button>
            <Button variant="outline" onClick={() => exportReport('doc')}>
              <FileDown className="w-4 h-4 mr-2" />
              Export DOC
            </Button>
            <Button variant="hero" onClick={() => selectedCase ? runCaseAnalysis(selectedCase) : toast.info("Select a case first")}>
              <Brain className="w-4 h-4 mr-2" />
              AI Analysis Mode
            </Button>
          </div>
        </div>

        {/* Stats */}
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 mb-8">
          {[
            { label: "Active Cases", value: stats.activeCases.toString(), icon: Briefcase, change: `${cases.length} total` },
            { label: "Pending Hearings", value: stats.pendingHearings.toString(), icon: Clock, change: "Next: Tomorrow" },
            { label: "AI Analyses Done", value: stats.aiAnalyses.toString(), icon: Brain, change: "Real-time" },
            { label: "Success Rate", value: `${stats.successRate}%`, icon: BarChart3, change: "↑ 3% vs last month" },
          ].map((stat) => {
            const Icon = stat.icon;
            return (
              <Card key={stat.label} variant="agent" className="p-4">
                <div className="flex items-start justify-between">
                  <div>
                    <p className="text-sm text-muted-foreground">{stat.label}</p>
                    <p className="text-2xl font-bold font-serif mt-1">{stat.value}</p>
                    <p className="text-xs text-primary mt-1">{stat.change}</p>
                  </div>
                  <div className="w-10 h-10 rounded-full bg-gradient-to-br from-primary to-gold-light flex items-center justify-center">
                    <Icon className="w-5 h-5 text-primary-foreground" />
                  </div>
                </div>
              </Card>
            );
          })}
        </div>

        <div className="grid lg:grid-cols-3 gap-8">
          {/* Cases List */}
          <div className="lg:col-span-2 space-y-4">
            {/* Search */}
            <Card variant="glass" className="p-4">
              <div className="flex gap-3">
                <div className="relative flex-1">
                  <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" />
                  <input
                    type="text"
                    placeholder="Search cases, clients, or sections..."
                    value={searchQuery}
                    onChange={(e) => setSearchQuery(e.target.value)}
                    className="w-full bg-muted border border-primary/30 rounded-lg pl-10 pr-4 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-primary/50"
                  />
                </div>
                <Button variant="outline">
                  <Filter className="w-4 h-4 mr-2" />
                  Filters
                </Button>
              </div>
            </Card>

            {/* Cases */}
            {loading ? (
              <div className="flex items-center justify-center py-12">
                <Loader2 className="w-8 h-8 animate-spin text-primary" />
              </div>
            ) : filteredCases.length === 0 ? (
              <Card variant="elevated" className="p-8 text-center">
                <Scale className="w-12 h-12 mx-auto mb-4 text-muted-foreground" />
                <p className="text-muted-foreground">No cases found</p>
                <Button variant="hero" className="mt-4" onClick={() => navigate('/case-intake')}>
                  File New Case
                </Button>
              </Card>
            ) : (
              <div className="space-y-4">
                {filteredCases.map((caseItem, index) => (
                  <Card 
                    key={caseItem.id} 
                    variant="elevated" 
                    className={`p-5 animate-fade-in-up cursor-pointer transition-all hover:border-primary/50 ${selectedCase?.id === caseItem.id ? 'border-primary' : ''}`}
                    style={{ animationDelay: `${index * 50}ms` }}
                    onClick={() => setSelectedCase(caseItem)}
                  >
                    <div className="flex items-start justify-between gap-4 mb-4">
                      <div>
                        <div className="flex items-center gap-2 mb-1">
                          <h3 className="font-serif font-semibold">{caseItem.title}</h3>
                          <Badge variant={getStatusColor(caseItem.status) as any} className="capitalize">
                            {caseItem.status.replace('_', ' ')}
                          </Badge>
                        </div>
                        <p className="text-sm text-muted-foreground">
                          {caseItem.category} • Created: {new Date(caseItem.created_at).toLocaleDateString('en-IN')}
                        </p>
                      </div>
                      <div className="flex gap-1">
                        <Button 
                          variant="ghost" 
                          size="icon"
                          onClick={(e) => { e.stopPropagation(); setSelectedCase(caseItem); setShowAnalysis(true); }}
                        >
                          <Eye className="w-4 h-4" />
                        </Button>
                        <Button 
                          variant="ghost" 
                          size="icon"
                          onClick={(e) => { e.stopPropagation(); generateLegalDraft(caseItem); }}
                        >
                          <Download className="w-4 h-4" />
                        </Button>
                      </div>
                    </div>

                    {getAllSections(caseItem).length > 0 && (
                      <div className="flex flex-wrap gap-1 mb-4">
                        {getAllSections(caseItem).slice(0, 5).map((section, idx) => (
                          <Badge key={`${section}-${idx}`} variant="judicial" className="text-xs">
                            {section}
                          </Badge>
                        ))}
                      </div>
                    )}

                    {caseItem.ai_analysis && (
                      <Card variant="glass" className="p-3 mb-3">
                        <div className="flex items-start gap-2">
                          <Brain className="w-4 h-4 text-primary mt-0.5" />
                          <div>
                            <p className="text-xs font-medium text-primary mb-1">AI Legal Analysis</p>
                            <p className="text-sm text-muted-foreground line-clamp-2">
                              {typeof caseItem.ai_analysis === 'object' && caseItem.ai_analysis.analysis 
                                ? caseItem.ai_analysis.analysis.slice(0, 200) + '...'
                                : 'Analysis available'}
                            </p>
                          </div>
                        </div>
                      </Card>
                    )}

                    <div className="flex items-center justify-between text-xs text-muted-foreground">
                      <span>Last updated: {new Date(caseItem.updated_at).toLocaleString('en-IN')}</span>
                      <Button 
                        variant="link" 
                        size="sm" 
                        className="h-auto p-0"
                        onClick={(e) => { e.stopPropagation(); runCaseAnalysis(caseItem); }}
                      >
                        {analyzing && selectedCase?.id === caseItem.id ? (
                          <>
                            <Loader2 className="w-3 h-3 mr-1 animate-spin" />
                            Analyzing...
                          </>
                        ) : (
                          <>
                            View Full Analysis
                            <ChevronRight className="w-3 h-3 ml-1" />
                          </>
                        )}
                      </Button>
                    </div>
                  </Card>
                ))}
              </div>
            )}
          </div>

          {/* Sidebar */}
          <div className="space-y-4">
            {/* AI Agents Status */}
            <Card variant="glass" className="p-4">
              <h3 className="font-serif font-semibold mb-4 flex items-center gap-2">
                <Brain className="w-4 h-4 text-primary" />
                AI Agents Status
              </h3>
              <AgentNetwork compact />
            </Card>

            {/* Quick Actions - ALL FUNCTIONAL */}
            <Card variant="glass" className="p-4">
              <h3 className="font-serif font-semibold mb-4">Quick Actions</h3>
              <div className="space-y-2">
                <Button 
                  variant="outline" 
                  className="w-full justify-start"
                  onClick={() => selectedCase ? runCaseAnalysis(selectedCase) : toast.info("Select a case first")}
                  disabled={analyzing}
                >
                  {analyzing ? (
                    <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                  ) : (
                    <Play className="w-4 h-4 mr-2" />
                  )}
                  Run Case Analysis
                  <ChevronRight className="w-4 h-4 ml-auto" />
                </Button>
                <Button 
                  variant="outline" 
                  className="w-full justify-start"
                  onClick={() => generateLegalDraft()}
                  disabled={generatingDraft}
                >
                  {generatingDraft ? (
                    <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                  ) : (
                    <FileText className="w-4 h-4 mr-2" />
                  )}
                  Generate Legal Draft
                  <ChevronRight className="w-4 h-4 ml-auto" />
                </Button>
                <div className="flex gap-2">
                  <input
                    type="text"
                    placeholder="e.g., IPC 420"
                    value={sectionQuery}
                    onChange={(e) => setSectionQuery(e.target.value)}
                    className="flex-1 bg-muted border border-primary/30 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-primary/50"
                    onKeyDown={(e) => e.key === 'Enter' && lookupSection()}
                  />
                  <Button 
                    variant="outline"
                    onClick={lookupSection}
                  >
                    <BookOpen className="w-4 h-4" />
                  </Button>
                </div>
              </div>
            </Card>

            {/* AI Reasoning Logs - REAL DATA */}
            <Card variant="glass" className="p-4">
              <h3 className="font-serif font-semibold mb-4">AI Reasoning Logs</h3>
              <div className="space-y-3 max-h-[300px] overflow-y-auto">
                {aiReasoningLogs.length === 0 ? (
                  <p className="text-sm text-muted-foreground">No recent activity</p>
                ) : (
                  aiReasoningLogs.map((log, index) => (
                    <div key={index} className="text-sm border-l-2 border-primary/30 pl-3">
                      <p className="text-xs text-muted-foreground">{log.time}</p>
                      <p className="font-medium text-primary">{log.action}</p>
                      <p className="text-muted-foreground text-xs">{log.desc}</p>
                    </div>
                  ))
                )}
              </div>
            </Card>
          </div>
        </div>
      </div>

      {/* Analysis Dialog */}
      <Dialog open={showAnalysis} onOpenChange={setShowAnalysis}>
        <DialogContent className="max-w-3xl max-h-[80vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <Gavel className="w-5 h-5 text-primary" />
              {selectedCase?.title || 'Case Analysis'}
            </DialogTitle>
            <DialogDescription>
              AI-powered legal analysis • Generated by Multi-Agent System
            </DialogDescription>
          </DialogHeader>
          
          {selectedCase && (
            <div className="space-y-4">
              <div className="grid grid-cols-2 gap-4 text-sm">
                <div>
                  <p className="text-muted-foreground">Category</p>
                  <p className="font-medium capitalize">{selectedCase.category}</p>
                </div>
                <div>
                  <p className="text-muted-foreground">Status</p>
                  <Badge variant={getStatusColor(selectedCase.status) as any} className="capitalize">
                    {selectedCase.status.replace('_', ' ')}
                  </Badge>
                </div>
              </div>

              {getAllSections(selectedCase).length > 0 && (
                <div>
                  <p className="text-sm text-muted-foreground mb-2">Applicable Sections</p>
                  <div className="flex flex-wrap gap-2">
                    {getAllSections(selectedCase).map((section, idx) => (
                      <Badge key={idx} variant="judicial">{section}</Badge>
                    ))}
                  </div>
                </div>
              )}

              <div>
                <p className="text-sm text-muted-foreground mb-2">Description</p>
                <p className="text-sm">{selectedCase.description}</p>
              </div>

              {selectedCase.ai_analysis && (
                <Card variant="parchment" className="p-4">
                  <div className="flex items-center gap-2 mb-3">
                    <Brain className="w-5 h-5 text-primary" />
                    <h4 className="font-serif font-semibold">AI Legal Analysis</h4>
                  </div>
                  <div className="prose prose-sm max-w-none text-secondary-foreground whitespace-pre-wrap">
                    {typeof selectedCase.ai_analysis === 'object' && selectedCase.ai_analysis.analysis 
                      ? selectedCase.ai_analysis.analysis
                      : JSON.stringify(selectedCase.ai_analysis, null, 2)}
                  </div>
                </Card>
              )}

              <div className="flex gap-2 pt-4 border-t">
                <Button variant="hero" onClick={() => generateLegalDraft(selectedCase)} disabled={generatingDraft}>
                  {generatingDraft ? <Loader2 className="w-4 h-4 mr-2 animate-spin" /> : <FileText className="w-4 h-4 mr-2" />}
                  Generate Legal Draft
                </Button>
                <Button variant="outline" onClick={() => runCaseAnalysis(selectedCase)} disabled={analyzing}>
                  {analyzing ? <Loader2 className="w-4 h-4 mr-2 animate-spin" /> : <Brain className="w-4 h-4 mr-2" />}
                  Re-analyze
                </Button>
              </div>

              <p className="text-xs text-muted-foreground italic">
                ⚖️ Disclaimer: This AI analysis is for informational purposes only and does not constitute legal advice. 
                Please consult a qualified lawyer for specific legal matters.
              </p>
            </div>
          )}
        </DialogContent>
      </Dialog>
    </Layout>
  );
};

export default LawyerPortal;