import React from "react";
import { Layout } from "@/components/Layout";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { AlertTriangle, Scale, Shield, BookOpen, HelpCircle, CheckCircle } from "lucide-react";

const LegalDisclaimer: React.FC = () => {
  return (
    <Layout>
      <div className="container mx-auto px-4 py-8 max-w-4xl">
        <div className="text-center mb-12">
          <AlertTriangle className="w-16 h-16 mx-auto text-warning mb-4" />
          <h1 className="font-serif text-4xl font-bold mb-4">Legal Disclaimer</h1>
          <p className="text-muted-foreground">
            Important information about AI LeXa Lawyer services under Indian Law
          </p>
        </div>

        <div className="space-y-6">
          {/* Primary Disclaimer */}
          <Card className="border-warning/50 bg-warning/5">
            <CardHeader>
              <CardTitle className="flex items-center gap-2 text-warning">
                <AlertTriangle className="w-5 h-5" />
                Primary Disclaimer
              </CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-foreground text-lg leading-relaxed">
                AI LeXa Lawyer is an AI-powered legal information platform. <strong>We do NOT provide legal advice, legal representation, or attorney-client relationships.</strong> The information provided through this platform is for general informational and educational purposes only.
              </p>
            </CardContent>
          </Card>

          <Card variant="glass">
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Scale className="w-5 h-5 text-primary" />
                Not a Substitute for Legal Counsel
              </CardTitle>
            </CardHeader>
            <CardContent className="prose prose-invert max-w-none">
              <p className="text-muted-foreground">
                As mandated by the Advocates Act, 1961 and the Bar Council of India Rules:
              </p>
              <ul className="list-disc pl-6 space-y-2 text-muted-foreground">
                <li>Only advocates registered with the Bar Council of India are authorized to practice law and provide legal advice in India.</li>
                <li>AI-generated legal guidance cannot and should not replace consultation with a qualified legal professional.</li>
                <li>Any legal documents generated by this platform are <strong>draft templates only</strong> and require verification by a licensed advocate.</li>
                <li>FIR drafts generated are for your reference to understand the format; actual FIRs must be filed at the police station.</li>
              </ul>
            </CardContent>
          </Card>

          <Card variant="glass">
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <BookOpen className="w-5 h-5 text-primary" />
                Accuracy of Legal Information
              </CardTitle>
            </CardHeader>
            <CardContent className="prose prose-invert max-w-none">
              <ul className="list-disc pl-6 space-y-2 text-muted-foreground">
                <li>Our AI references the Indian Penal Code (IPC), Bharatiya Nyaya Sanhita (BNS), Code of Criminal Procedure (CrPC), and the Constitution of India.</li>
                <li>Laws are subject to amendments, and our database may not reflect the most recent changes.</li>
                <li>Court interpretations and precedents may vary; AI cannot account for all judicial nuances.</li>
                <li>State-specific laws and local variations may not be fully covered.</li>
                <li>The transition from IPC to BNS (effective 1st July 2024) may create complexities that require professional guidance.</li>
              </ul>
            </CardContent>
          </Card>

          <Card variant="glass">
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Shield className="w-5 h-5 text-primary" />
                No Liability
              </CardTitle>
            </CardHeader>
            <CardContent className="prose prose-invert max-w-none">
              <p className="text-muted-foreground mb-4">
                AI LeXa Lawyer, its creators, and affiliates shall not be held liable for:
              </p>
              <ul className="list-disc pl-6 space-y-2 text-muted-foreground">
                <li>Any actions taken based on information provided by this platform.</li>
                <li>Inaccuracies, errors, or omissions in AI-generated content.</li>
                <li>Legal outcomes or consequences arising from use of our services.</li>
                <li>Loss of evidence, missed deadlines, or procedural errors resulting from reliance on AI guidance.</li>
                <li>Emotional distress or financial losses incurred.</li>
              </ul>
            </CardContent>
          </Card>

          <Card variant="glass">
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <HelpCircle className="w-5 h-5 text-primary" />
                When to Seek Immediate Legal Help
              </CardTitle>
            </CardHeader>
            <CardContent className="prose prose-invert max-w-none">
              <p className="text-muted-foreground mb-4">
                Please consult a qualified advocate immediately if:
              </p>
              <ul className="list-disc pl-6 space-y-2 text-muted-foreground">
                <li>You are facing arrest or have been arrested (contact a criminal lawyer immediately).</li>
                <li>You have received a court summons or legal notice.</li>
                <li>You are involved in ongoing litigation.</li>
                <li>Your matter involves significant financial interests.</li>
                <li>There are time-sensitive limitations (under the Limitation Act, 1963).</li>
                <li>The matter involves minors, domestic violence, or sensitive personal issues.</li>
              </ul>
            </CardContent>
          </Card>

          <Card variant="glass">
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <CheckCircle className="w-5 h-5 text-primary" />
                Appropriate Use of This Platform
              </CardTitle>
            </CardHeader>
            <CardContent className="prose prose-invert max-w-none">
              <p className="text-muted-foreground mb-4">
                This platform is appropriately used for:
              </p>
              <ul className="list-disc pl-6 space-y-2 text-muted-foreground">
                <li>General understanding of Indian legal concepts and procedures.</li>
                <li>Preliminary assessment of legal issues before consulting a lawyer.</li>
                <li>Learning about relevant laws and legal sections applicable to common situations.</li>
                <li>Generating draft documents to understand proper formats.</li>
                <li>Finding information about legal rights and remedies under Indian law.</li>
              </ul>
            </CardContent>
          </Card>

          <Card variant="parchment">
            <CardContent className="py-8 text-center">
              <Scale className="w-12 h-12 mx-auto text-primary mb-4" />
              <h3 className="font-serif text-xl font-bold text-secondary-foreground mb-4">
                Acknowledgment
              </h3>
              <p className="text-secondary-foreground mb-4">
                By using AI LeXa Lawyer, you acknowledge that you have read, understood, and accept this Legal Disclaimer in its entirety. You agree that you will seek professional legal advice for matters affecting your legal rights and obligations.
              </p>
              <p className="text-secondary-foreground text-sm">
                <strong>Emergency Legal Aid:</strong> National Legal Services Authority (NALSA) Helpline: 15100
              </p>
            </CardContent>
          </Card>
        </div>
      </div>
    </Layout>
  );
};

export default LegalDisclaimer;
