import React from "react";
import { Layout } from "@/components/Layout";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { AlertTriangle, Scale, Shield, BookOpen, UserX, Info } from "lucide-react";

const LegalDisclaimer: React.FC = () => {
  return (
    <Layout>
      <div className="container mx-auto px-4 py-12">
        <div className="max-w-4xl mx-auto">
          <div className="text-center mb-12">
            <AlertTriangle className="w-16 h-16 mx-auto text-warning mb-4" />
            <h1 className="font-serif text-4xl font-bold mb-4">Legal Disclaimer</h1>
            <p className="text-muted-foreground">
              Important Information About Our Services
            </p>
          </div>

          <Card variant="glass" className="mb-8 border-warning/50">
            <CardContent className="pt-6">
              <div className="flex items-start gap-4">
                <AlertTriangle className="w-8 h-8 text-warning flex-shrink-0" />
                <div>
                  <h3 className="font-serif font-bold text-lg mb-2">Critical Notice</h3>
                  <p className="text-muted-foreground">
                    AI LeXa Lawyer is an AI-powered legal information platform. <strong>We do not provide legal advice, legal representation, or act as your attorney.</strong> The information provided through this platform is for educational and informational purposes only and should not be construed as legal advice.
                  </p>
                </div>
              </div>
            </CardContent>
          </Card>

          <div className="space-y-8">
            <Card variant="elevated">
              <CardHeader>
                <CardTitle className="flex items-center gap-2 font-serif">
                  <Scale className="w-5 h-5 text-primary" />
                  Nature of Services
                </CardTitle>
              </CardHeader>
              <CardContent className="prose prose-sm max-w-none text-muted-foreground">
                <p>
                  The AI LeXa Lawyer platform provides:
                </p>
                <ul>
                  <li><strong>Legal Information:</strong> General information about Indian laws, legal procedures, and rights</li>
                  <li><strong>Document Templates:</strong> Draft templates for FIRs, complaints, and other legal documents</li>
                  <li><strong>AI Guidance:</strong> AI-generated responses based on legal databases and precedents</li>
                  <li><strong>Educational Content:</strong> Resources to help understand the Indian legal system</li>
                </ul>
                <p>
                  These services are designed to assist citizens in understanding their legal rights and options. They are not substitutes for professional legal advice from a qualified advocate.
                </p>
              </CardContent>
            </Card>

            <Card variant="elevated">
              <CardHeader>
                <CardTitle className="flex items-center gap-2 font-serif">
                  <UserX className="w-5 h-5 text-primary" />
                  No Attorney-Client Relationship
                </CardTitle>
              </CardHeader>
              <CardContent className="prose prose-sm max-w-none text-muted-foreground">
                <p>
                  Use of this platform does not create an attorney-client relationship between you and AI LeXa Lawyer or any of its operators, developers, or affiliates.
                </p>
                <ul>
                  <li>The AI system is not a licensed legal practitioner</li>
                  <li>No confidential attorney-client privilege applies to your communications</li>
                  <li>The platform cannot represent you in court or before any authority</li>
                  <li>Responses are generated by artificial intelligence, not human lawyers</li>
                </ul>
              </CardContent>
            </Card>

            <Card variant="elevated">
              <CardHeader>
                <CardTitle className="flex items-center gap-2 font-serif">
                  <BookOpen className="w-5 h-5 text-primary" />
                  Accuracy of Information
                </CardTitle>
              </CardHeader>
              <CardContent className="prose prose-sm max-w-none text-muted-foreground">
                <p>While we strive to provide accurate and up-to-date information:</p>
                <ul>
                  <li>Laws and legal interpretations may change frequently</li>
                  <li>AI responses may contain errors or outdated information</li>
                  <li>Legal provisions may vary based on jurisdiction and specific circumstances</li>
                  <li>The AI may not account for all relevant factors in your case</li>
                  <li>Court interpretations and judicial precedents evolve continuously</li>
                </ul>
                <p>
                  <strong>Always verify information</strong> with official sources such as the India Code, Supreme Court judgments, or qualified legal professionals before taking any action.
                </p>
              </CardContent>
            </Card>

            <Card variant="elevated">
              <CardHeader>
                <CardTitle className="flex items-center gap-2 font-serif">
                  <Shield className="w-5 h-5 text-primary" />
                  Limitation of Liability
                </CardTitle>
              </CardHeader>
              <CardContent className="prose prose-sm max-w-none text-muted-foreground">
                <p>
                  To the fullest extent permitted by law, AI LeXa Lawyer and its operators shall not be liable for:
                </p>
                <ul>
                  <li>Any damages arising from reliance on information provided by the platform</li>
                  <li>Losses resulting from actions taken based on AI-generated guidance</li>
                  <li>Consequences of filing documents based on platform-generated drafts</li>
                  <li>Any indirect, incidental, special, or consequential damages</li>
                  <li>Legal outcomes in any proceedings</li>
                </ul>
                <p>
                  <strong>You assume full responsibility</strong> for any decisions made and actions taken based on information obtained from this platform.
                </p>
              </CardContent>
            </Card>

            <Card variant="elevated">
              <CardHeader>
                <CardTitle className="flex items-center gap-2 font-serif">
                  <Info className="w-5 h-5 text-primary" />
                  When to Seek Professional Help
                </CardTitle>
              </CardHeader>
              <CardContent className="prose prose-sm max-w-none text-muted-foreground">
                <p>
                  You should consult a qualified advocate if:
                </p>
                <ul>
                  <li>You are facing criminal charges or investigation</li>
                  <li>You need to file a court case or respond to legal notices</li>
                  <li>Your matter involves significant financial stakes</li>
                  <li>You are dealing with family law matters (divorce, custody, etc.)</li>
                  <li>You need representation before any court or tribunal</li>
                  <li>Your case involves complex legal issues</li>
                  <li>Time-sensitive legal deadlines are involved</li>
                </ul>
              </CardContent>
            </Card>

            <Card variant="parchment">
              <CardContent className="pt-6">
                <div className="text-center">
                  <Scale className="w-12 h-12 mx-auto text-primary/80 mb-4" />
                  <p className="text-sm text-secondary-foreground italic">
                    "Justice delayed is justice denied, but justice without proper guidance is justice compromised."
                  </p>
                  <p className="text-xs text-secondary-foreground mt-4">
                    For specific legal matters affecting your rights, liberty, or property, always consult a qualified advocate enrolled with the Bar Council of India.
                  </p>
                </div>
              </CardContent>
            </Card>
          </div>
        </div>
      </div>
    </Layout>
  );
};

export default LegalDisclaimer;
